-- Define icon path prefix
local fluid_icon_path = "__Gregtorio__/graphics/fluids/"

-- Define base and flow colors for each unique icon
local fluid_colors_by_icon = {
  [fluid_icon_path .. "ammonia.png"] = { base_color = {r = 0.260, g = 0.350, b = 0.560}, flow_color = {r = 0.360, g = 0.450, b = 0.660} },
  [fluid_icon_path .. "biomass.png"] = { base_color = {r = 0.120, g = 0.420, b = 0.400}, flow_color = {r = 0.120, g = 0.420, b = 0.400} },
  [fluid_icon_path .. "black-fluid.png"] = { base_color = {r = 0.040, g = 0.050, b = 0.050}, flow_color = {r = 0.040, g = 0.050, b = 0.050} },
  [fluid_icon_path .. "brown-fluid.png"] = { base_color = {r = 0.440, g = 0.240, b = 0.070}, flow_color = {r = 0.580, g = 0.340, b = 0.120} },
  [fluid_icon_path .. "carbon-dioxide.png"] = { base_color = {r = 0.450, g = 0.620, b = 0.780}, flow_color = {r = 0.600, g = 0.750, b = 0.950} },
  [fluid_icon_path .. "chlorine.png"] = { base_color = {r = 0.120, g = 0.420, b = 0.400}, flow_color = {r = 0.120, g = 0.420, b = 0.400} },
  [fluid_icon_path .. "cryogenic-helium.png"] = { base_color = {r = 0.940, g = 0.940, b = 0.600}, flow_color = {r = 0.940, g = 0.940, b = 0.600} },
  [fluid_icon_path .. "dark-blue-spackled-fluid.png"] = { base_color = {r = 0.260, g = 0.350, b = 0.560}, flow_color = {r = 0.360, g = 0.450, b = 0.660} },
  [fluid_icon_path .. "dark-gray-spackled-fluid.png"] = { base_color = {r = 0.680, g = 0.640, b = 0.630}, flow_color = {r = 0.680, g = 0.640, b = 0.630} },
  [fluid_icon_path .. "dark-muted-yellow-fluid.png"] = { base_color = {r = 0.435, g = 0.431, b = 0.067}, flow_color = {r = 0.435, g = 0.431, b = 0.067} },
  [fluid_icon_path .. "deep-blue-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "deep-pink-fluid.png"] = { base_color =  { r = 0.78, g = 0.12, b = 0.78 }, flow_color = { r = 0.88, g = 0.2, b = 0.88 } },
  [fluid_icon_path .. "deuterium.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "ethane.png"] = { base_color = {r = 0.560, g = 0.580, b = 0.780}, flow_color = {r = 0.660, g = 0.680, b = 0.880} },
  [fluid_icon_path .. "enderium.png"] = { base_color = {r = 0.046, g = 0.384, b = 0.357}, flow_color = {r = 0.051, g = 0.422, b = 0.393} },
  [fluid_icon_path .. "fluorine.png"] = { base_color = {r = 0.200, g = 0.550, b = 0.880}, flow_color = {r = 0.350, g = 0.750, b = 1.000} },
  [fluid_icon_path .. "fluoroantimonic-acid.png"] = { base_color = {r = 0.600, g = 0.800, b = 1.000}, flow_color = {r = 0.700, g = 0.900, b = 1.000} },
  [fluid_icon_path .. "forest-green-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "glue.png"] = { base_color = {r = 0.930, g = 0.740, b = 0.490}, flow_color = {r = 0.930, g = 0.740, b = 0.490} },
  [fluid_icon_path .. "heavy-fuel.png"] = { base_color = {r = 0.980, g = 0.910, b = 0.650}, flow_color = {r = 1.000, g = 0.960, b = 0.800} },
  [fluid_icon_path .. "helium.png"] = { base_color = {r = 0.040, g = 0.050, b = 0.050}, flow_color = {r = 0.040, g = 0.050, b = 0.050} },
  [fluid_icon_path .. "imaginary-time.png"] = { base_color = {r = 0.408, g = 0.075, b = 0.639}, flow_color = {r = 0.408, g = 0.075, b = 0.639} },
  [fluid_icon_path .. "krypton.png"] = { base_color = {r = 0.120, g = 0.420, b = 0.400}, flow_color = {r = 0.120, g = 0.420, b = 0.400} },
  [fluid_icon_path .. "lava.png"] = { base_color = { r = 1.0, g = 0.32, b = 0.0 }, flow_color = { r = 1.0, g = 0.45, b = 0.1 } },
  [fluid_icon_path .. "light-fuel.png"] = { base_color = {r = 0.880, g = 0.900, b = 0.120}, flow_color = {r = 1.000, g = 1.000, b = 0.250} },
  [fluid_icon_path .. "light-orange-fluid.png"] = { base_color = {r = 0.830, g = 0.560, b = 0.230}, flow_color = {r = 0.830, g = 0.560, b = 0.230} },
  [fluid_icon_path .. "light-pink-fluid.png"] = { base_color = {r = 0.780, g = 0.530, b = 0.530}, flow_color = {r = 0.920, g = 0.660, b = 0.660} },
  [fluid_icon_path .. "liquid-blaze.png"] = { base_color = {r = 1.000, g = 0.580, b = 0.000}, flow_color = {r = 1.000, g = 0.720, b = 0.150} },
  [fluid_icon_path .. "liquid-ender-air.png"] = { base_color = {r = 0.620, g = 0.740, b = 0.820}, flow_color = {r = 0.720, g = 0.840, b = 0.920} },
  [fluid_icon_path .. "liquid-nether-air.png"] = { base_color = {r = 0.620, g = 0.740, b = 0.820}, flow_color = {r = 0.720, g = 0.840, b = 0.920} },
  [fluid_icon_path .. "lubricant.png"] = { base_color = {r = 0.950, g = 0.800, b = 0.550}, flow_color = {r = 0.950, g = 0.800, b = 0.550} },
  [fluid_icon_path .. "medium-gray-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "medium-green-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "medium-red-fluid.png"] = { base_color = {r = 0.600, g = 0.150, b = 0.150}, flow_color = {r = 0.800, g = 0.200, b = 0.200} },
  [fluid_icon_path .. "methane.png"] = { base_color = {r = 0.800, g = 0.070, b = 0.450}, flow_color = {r = 0.950, g = 0.200, b = 0.600} },
  [fluid_icon_path .. "methanol.png"] = { base_color = {r = 0.480, g = 0.400, b = 0.030}, flow_color = {r = 0.580, g = 0.500, b = 0.130} },
  [fluid_icon_path .. "molten-hsse.png"] = { base_color = {r = 0.380, g = 0.340, b = 0.530}, flow_color = {r = 0.380, g = 0.340, b = 0.530} },
  [fluid_icon_path .. "molten-hssg.png"] = { base_color = {r = 0.480, g = 0.280, b = 0.560}, flow_color = {r = 0.480, g = 0.280, b = 0.560} },
  [fluid_icon_path .. "molten-hsss.png"] = { base_color = {r = 0.830, g = 0.560, b = 0.230}, flow_color = {r = 0.830, g = 0.560, b = 0.230} },
  [fluid_icon_path .. "molten-tungstensteel.png"] = { base_color = {r = 0.260, g = 0.350, b = 0.560}, flow_color = {r = 0.360, g = 0.450, b = 0.660} },
  [fluid_icon_path .. "naphtha.png"] = { base_color = {r = 0.900, g = 0.890, b = 0.090}, flow_color = {r = 1.000, g = 1.000, b = 0.200} },
  [fluid_icon_path .. "nearly-white-fluid.png"] = { base_color = {r = 0.850, g = 0.850, b = 0.850}, flow_color = {r = 0.950, g = 0.950, b = 0.950} },
  [fluid_icon_path .. "neon.png"] = { base_color = {r = 0.824, g = 0.329, b = 0.427}, flow_color = {r = 0.824, g = 0.329, b = 0.427} },
  [fluid_icon_path .. "nitrogen.png"] = { base_color = {r = 0.000, g = 0.700, b = 0.700}, flow_color = {r = 0.000, g = 0.900, b = 0.900} },
  [fluid_icon_path .. "olive-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "orange-fluid.png"] = { base_color = {r = 0.870, g = 0.450, b = 0.100}, flow_color = {r = 1.000, g = 0.600, b = 0.200} },
  [fluid_icon_path .. "oxygen.png"] = { base_color = {r = 0.600, g = 0.800, b = 1.000}, flow_color = {r = 0.700, g = 0.900, b = 1.000} },
  [fluid_icon_path .. "pale-green-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "phenol.png"] = { base_color = {r = 0.390, g = 0.230, b = 0.080}, flow_color = {r = 0.390, g = 0.230, b = 0.080} },
  [fluid_icon_path .. "propane.png"] = { base_color = {r = 0.820, g = 0.760, b = 0.250}, flow_color = {r = 0.950, g = 0.880, b = 0.350} },
  [fluid_icon_path .. "purple-fluid.png"] = { base_color = {r = 0.500, g = 0.200, b = 0.530}, flow_color = {r = 0.500, g = 0.200, b = 0.530} },
  [fluid_icon_path .. "rich-green-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "rocket-fuel.png"] = { base_color = {r = 0.560, g = 0.520, b = 0.360}, flow_color = {r = 0.720, g = 0.680, b = 0.450} },
  [fluid_icon_path .. "ruby-juice.png"] = { base_color = {r = 0.600, g = 0.150, b = 0.150}, flow_color = {r = 0.800, g = 0.200, b = 0.200} },
  [fluid_icon_path .. "rust-brown-fluid.png"] = { base_color = {r = 0.500, g = 0.180, b = 0.050}, flow_color = {r = 0.650, g = 0.280, b = 0.100} },
  [fluid_icon_path .. "silver-blue-spackled-fluid.png"] = { base_color = {r = 0.620, g = 0.740, b = 0.820}, flow_color = {r = 0.720, g = 0.840, b = 0.920} },
  [fluid_icon_path .. "soldering-alloy.png"] = { base_color = {r = 0.050, g = 0.100, b = 0.300}, flow_color = {r = 0.100, g = 0.200, b = 0.500} },
  [fluid_icon_path .. "spackled-brown-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "spackled-copper-fluid.png"] = { base_color = {r = 0.830, g = 0.480, b = 0.290}, flow_color = {r = 0.950, g = 0.600, b = 0.400} },
  [fluid_icon_path .. "spackled-forest-green-fluid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "spackled-gray-fluid.png"] = { base_color = {r = 0.680, g = 0.640, b = 0.630}, flow_color = {r = 0.680, g = 0.640, b = 0.630} },
  [fluid_icon_path .. "spackled-light-blue-fluid.png"] = { base_color = {r = 0.620, g = 0.740, b = 0.820}, flow_color = {r = 0.720, g = 0.840, b = 0.920} },
  [fluid_icon_path .. "spackled-medium-blue-fluid.png"] = { base_color = {r = 0.000, g = 0.580, b = 0.660}, flow_color = {r = 0.000, g = 0.580, b = 0.660} },
  [fluid_icon_path .. "spackled-medium-gray-fluid.png"] = { base_color = {r = 0.680, g = 0.640, b = 0.630}, flow_color = {r = 0.680, g = 0.640, b = 0.630} },
  [fluid_icon_path .. "spackled-mint-green-fluid.png"] = { base_color = {r = 0.500, g = 0.950, b = 0.850}, flow_color = {r = 0.600, g = 1.000, b = 0.950} },
  [fluid_icon_path .. "spackled-orange-fluid.png"] = { base_color = {r = 0.870, g = 0.450, b = 0.100}, flow_color = {r = 1.000, g = 0.600, b = 0.200} },
  [fluid_icon_path .. "spackled-purple-fluid.png"] = { base_color = {r = 0.360, g = 0.270, b = 0.420}, flow_color = {r = 0.360, g = 0.270, b = 0.420} },
  [fluid_icon_path .. "spackled-rich-brown-fluid.png"] = { base_color = {r = 0.330, g = 0.110, b = 0.040}, flow_color = {r = 0.450, g = 0.180, b = 0.080} },
  [fluid_icon_path .. "spackled-silvery-gold-fluid.png"] = { base_color = {r = 0.790, g = 0.790, b = 0.600}, flow_color = {r = 0.790, g = 0.790, b = 0.600} },
  [fluid_icon_path .. "spackled-yellow-fluid.png"] = { base_color = {r = 0.730, g = 0.720, b = 0.100}, flow_color = {r = 0.950, g = 0.950, b = 0.200} },
  [fluid_icon_path .. "sulfuric-acid.png"] = { base_color = {r = 0.980, g = 0.950, b = 0.560}, flow_color = {r = 0.980, g = 0.950, b = 0.560} },
  [fluid_icon_path .. "titanium.png"] = { base_color = {r = 0.750, g = 0.500, b = 0.660}, flow_color = {r = 0.750, g = 0.500, b = 0.660} },
  [fluid_icon_path .. "tritium.png"] = { base_color = {r = 0.498, g = 0.996, b = 0.498}, flow_color = {r = 0.498, g = 0.996, b = 0.498} },
  [fluid_icon_path .. "water.png"] = { base_color = { r = 0.0, g = 0.34, b = 0.6 }, flow_color = { r = 0.7, g = 0.7, b = 0.7 } },
  [fluid_icon_path .. "wood-tar.png"] = { base_color = {r = 0.050, g = 0.100, b = 0.300}, flow_color = {r = 0.100, g = 0.200, b = 0.500} },
  [fluid_icon_path .. "xenon.png"] = { base_color = {r = 0.020, g = 0.682, b = 0.682}, flow_color = {r = 0.020, g = 0.682, b = 0.682} },
}

-- Create a helper function to define a fluid
local function make_fluid(name, icon)
  local colors = fluid_colors_by_icon[icon] or { base_color = {r = 1, g = 0, b = 1}, flow_color = {r = 1, g = 0, b = 1} }
  return {
    type = "fluid",
    name = name,
    default_temperature = 1000,
    max_temperature = 1000,
    heat_capacity = "0.1kJ",
    base_color = colors.base_color,
    flow_color = colors.flow_color,
    icon = icon,
    icon_size = 32,
    order = "a[fluid]-z[" .. name .. "]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    auto_barrel = false
  }
end

-- Create all fluids
local fluids = {
  make_fluid("acetic-acid", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("acetone", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("acidic-iridium-dioxide-solution", fluid_icon_path .. "dark-blue-spackled-fluid.png"),
  make_fluid("acidic-osmium-solution", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("advanced-glue", fluid_icon_path .. "medium-red-fluid.png"),
  make_fluid("air", fluid_icon_path .. "medium-gray-fluid.png"),
  make_fluid("ammonia", fluid_icon_path .. "ammonia.png"),
  make_fluid("antimony-pentachloride", fluid_icon_path .. "rich-green-fluid.png"),
  make_fluid("antimony-pentachloride-solution", fluid_icon_path .. "pale-green-fluid.png"),
  make_fluid("antimony-pentafluoride", fluid_icon_path .. "fluoroantimonic-acid.png"),
  make_fluid("antimony-trichloride-solution", fluid_icon_path .. "biomass.png"),
  make_fluid("aqua-regia", fluid_icon_path .. "spackled-orange-fluid.png"),
  make_fluid("argon", fluid_icon_path .. "medium-green-fluid.png"),
  make_fluid("bauxite-slurry", fluid_icon_path .. "spackled-light-blue-fluid.png"),
  make_fluid("benzene", fluid_icon_path .. "black-fluid.png"),
  make_fluid("biomass", fluid_icon_path .. "biomass.png"),
  make_fluid("butadiene", fluid_icon_path .. "brown-fluid.png"),
  make_fluid("butene", fluid_icon_path .. "rust-brown-fluid.png"),
  make_fluid("butyraldehyde", fluid_icon_path .. "phenol.png"),
  make_fluid("carbon-dioxide", fluid_icon_path .. "carbon-dioxide.png"),
  make_fluid("carbon-monoxide", fluid_icon_path .. "carbon-dioxide.png"),
  make_fluid("cetane-boosted-diesel", fluid_icon_path .. "naphtha.png"),
  make_fluid("charcoal-byproducts", fluid_icon_path .. "spackled-brown-fluid.png"),
  make_fluid("chlorine", fluid_icon_path .. "chlorine.png"),
  make_fluid("chlorobenzene", fluid_icon_path .. "pale-green-fluid.png"),
  make_fluid("chloroform", fluid_icon_path .. "purple-fluid.png"),
  make_fluid("chloroplatinic-acid", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("creosote", fluid_icon_path .. "dark-muted-yellow-fluid.png"),
  make_fluid("crude-oil", fluid_icon_path .. "black-fluid.png"),
  make_fluid("cryogenic-helium", fluid_icon_path .. "cryogenic-helium.png"),
  make_fluid("depleted-uranium-hexafluoride", fluid_icon_path .. "pale-green-fluid.png"),
  make_fluid("deuterium", fluid_icon_path .. "deuterium.png"),
  make_fluid("diaminobenzidine", fluid_icon_path .. "forest-green-fluid.png"),
  make_fluid("dichlorobenzene", fluid_icon_path .. "spackled-medium-blue-fluid.png"),
  make_fluid("dichlorobenzidine", fluid_icon_path .. "spackled-mint-green-fluid.png"),
  make_fluid("diesel", fluid_icon_path .. "light-fuel.png"),
  make_fluid("diluted-hydrochloric-acid", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("diluted-sulfuric-acid", fluid_icon_path .. "spackled-brown-fluid.png"),
  make_fluid("dimethylbenzene", fluid_icon_path .. "pale-green-fluid.png"),
  make_fluid("dimethylhydrazine", fluid_icon_path .. "deep-blue-fluid.png"),
  make_fluid("dinitrogen-tetroxide", fluid_icon_path .. "nitrogen.png"),
  make_fluid("diphenyl-isophthalate", fluid_icon_path .. "forest-green-fluid.png"),
  make_fluid("distilled-water", fluid_icon_path .. "oxygen.png"),
  make_fluid("ender-air", fluid_icon_path .. "liquid-ender-air.png"),
  make_fluid("enriched-naquadah-rich-solution", fluid_icon_path .. "spackled-rich-brown-fluid.png"),
  make_fluid("enriched-uranium-hexafluoride", fluid_icon_path .. "medium-green-fluid.png"),
  make_fluid("epichlorohydrin", fluid_icon_path .. "spackled-rich-brown-fluid.png"),
  make_fluid("epoxy", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("ethane", fluid_icon_path .. "ethane.png"),
  make_fluid("ethanol", fluid_icon_path .. "spackled-brown-fluid.png"),
  make_fluid("ether", fluid_icon_path .. "light-fuel.png"),
  make_fluid("ethylene", fluid_icon_path .. "medium-gray-fluid.png"),
  make_fluid("exhausted-water", fluid_icon_path .. "water.png"),
  make_fluid("fluorine", fluid_icon_path .. "fluorine.png"),
  make_fluid("fluorine-rich-waste-liquid", fluid_icon_path .. "krypton.png"),
  make_fluid("fluoroantimonic-acid", fluid_icon_path .. "fluoroantimonic-acid.png"),
  make_fluid("formic-acid", fluid_icon_path .. "medium-gray-fluid.png"),
  make_fluid("gasoline", fluid_icon_path .. "sulfuric-acid.png"),
  make_fluid("glue", fluid_icon_path .. "glue.png"),
  make_fluid("grade-1-water", fluid_icon_path .. "water.png"),
  make_fluid("grade-2-water", fluid_icon_path .. "water.png"),
  make_fluid("grade-3-water", fluid_icon_path .. "water.png"),
  make_fluid("grade-4-water", fluid_icon_path .. "water.png"),
  make_fluid("grade-5-water", fluid_icon_path .. "water.png"),
  make_fluid("grade-6-water", fluid_icon_path .. "water.png"),
  make_fluid("grade-7-water", fluid_icon_path .. "water.png"),
  make_fluid("grade-8-water", fluid_icon_path .. "water.png"),
  make_fluid("heated-bauxite-slurry", fluid_icon_path .. "deep-blue-fluid.png"),
  make_fluid("heavy-fuel", fluid_icon_path .. "heavy-fuel.png"),
  make_fluid("helium", fluid_icon_path .. "helium.png"),
  make_fluid("helium-3", fluid_icon_path .. "helium.png"),
  make_fluid("high-octane-gasoline", fluid_icon_path .. "sulfuric-acid.png"),
  make_fluid("hydrochloric-acid", fluid_icon_path .. "medium-gray-fluid.png"),
  make_fluid("hydrofluoric-acid", fluid_icon_path .. "spackled-medium-blue-fluid.png"),
  make_fluid("hydrogen", fluid_icon_path .. "deep-blue-fluid.png"),
  make_fluid("hydrogen-peroxide", fluid_icon_path .. "silver-blue-spackled-fluid.png"),
  make_fluid("hydrogen-sulfide", fluid_icon_path .. "orange-fluid.png"),
  make_fluid("hypochlorous-acid", fluid_icon_path .. "soldering-alloy.png"),
  make_fluid("imaginary-time", fluid_icon_path .. "imaginary-time.png"),
  make_fluid("indium-concentrate", fluid_icon_path .. "deep-blue-fluid.png"),
  make_fluid("iron-iii-chloride", fluid_icon_path .. "black-fluid.png"),
  make_fluid("krypton", fluid_icon_path .. "krypton.png"),
  make_fluid("lapis-coolant", fluid_icon_path .. "dark-blue-spackled-fluid.png"),
  make_fluid("lava", fluid_icon_path .. "lava.png"),
  make_fluid("lead-zinc-solution", fluid_icon_path .. "spackled-rich-brown-fluid.png"),
  make_fluid("light-fuel", fluid_icon_path .. "light-fuel.png"),
  make_fluid("liquid-air", fluid_icon_path .. "spackled-light-blue-fluid.png"),
  make_fluid("liquid-blaze", fluid_icon_path .. "liquid-blaze.png"),
  make_fluid("liquid-concrete", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("liquid-ender-air", fluid_icon_path .. "liquid-ender-air.png"),
  make_fluid("liquid-nether-air", fluid_icon_path .. "liquid-nether-air.png"),
  make_fluid("liquid-rubber", fluid_icon_path .. "black-fluid.png"),
  make_fluid("low-quality-naquadah-emulsion", fluid_icon_path .. "medium-gray-fluid.png"),
  make_fluid("low-quality-naquadah-solution", fluid_icon_path .. "spackled-medium-gray-fluid.png"),
  make_fluid("low-quality-naquadria-sulphate-solution", fluid_icon_path .. "phenol.png"),
  make_fluid("lubricant", fluid_icon_path .. "lubricant.png"),
  make_fluid("mercury", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("methane", fluid_icon_path .. "methane.png"),
  make_fluid("methanol", fluid_icon_path .. "methanol.png"),
  make_fluid("methyl-acetate", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("molten-aluminium", fluid_icon_path .. "spackled-light-blue-fluid.png"),
  make_fluid("molten-black-steel", fluid_icon_path .. "black-fluid.png"),
  make_fluid("molten-blue-steel", fluid_icon_path .. "molten-tungstensteel.png"),
  make_fluid("molten-borosilicate-glass", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("molten-cupronickel", fluid_icon_path .. "spackled-copper-fluid.png"),
  make_fluid("molten-enderium", fluid_icon_path .. "enderium.png"),
  make_fluid("molten-glass", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("molten-glowstone", fluid_icon_path .. "light-orange-fluid.png"),
  make_fluid("molten-grisium", fluid_icon_path .. "light-orange-fluid.png"),
  make_fluid("molten-hastelloy-c276", fluid_icon_path .. "molten-hsse.png"),
  make_fluid("molten-hastelloy-w", fluid_icon_path .. "molten-hsse.png"),
  make_fluid("molten-hastelloy-x", fluid_icon_path .. "molten-hsse.png"),
  make_fluid("molten-hsse", fluid_icon_path .. "molten-hsse.png"),
  make_fluid("molten-hssg", fluid_icon_path .. "molten-hssg.png"),
  make_fluid("molten-hsss", fluid_icon_path .. "molten-hsss.png"),
  make_fluid("molten-indalloy-140", fluid_icon_path .. "spackled-forest-green-fluid.png"),
  make_fluid("molten-incoloy-ma956", fluid_icon_path .. "spackled-forest-green-fluid.png"),
  make_fluid("molten-incoloy-020", fluid_icon_path .. "light-pink-fluid.png"),
  make_fluid("molten-incoloy-ds", fluid_icon_path .. "spackled-light-blue-fluid.png"),
  make_fluid("molten-inconel-625", fluid_icon_path .. "light-pink-fluid.png"),
  make_fluid("molten-inconel-690", fluid_icon_path .. "light-pink-fluid.png"),
  make_fluid("molten-inconel-792", fluid_icon_path .. "light-pink-fluid.png"),
  make_fluid("molten-incoloy-903", fluid_icon_path .. "light-pink-fluid.png"),
  make_fluid("molten-indovanadium", fluid_icon_path .. "purple-fluid.png"),
  make_fluid("molten-kanthal", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("molten-maraging-steel-250", fluid_icon_path .. "purple-fluid.png"),
  make_fluid("molten-maraging-steel-300", fluid_icon_path .. "purple-fluid.png"),
  make_fluid("molten-microversium", fluid_icon_path .. "purple-fluid.png"),
  make_fluid("molten-naquadah-alloy", fluid_icon_path .. "black-fluid.png"),
  make_fluid("molten-nichrome", fluid_icon_path .. "spackled-purple-fluid.png"),
  make_fluid("molten-nickel-zinc-ferrite", fluid_icon_path .. "phenol.png"),
  make_fluid("molten-nitinol-60", fluid_icon_path .. "molten-hsss.png"),
  make_fluid("molten-niobium-titanium", fluid_icon_path .. "molten-hsse.png"),
  make_fluid("molten-niobium-titanium", fluid_icon_path .. "molten-hsse.png"),
  make_fluid("molten-red-alloy", fluid_icon_path .. "medium-red-fluid.png"),
  make_fluid("molten-rtm-alloy", fluid_icon_path .. "molten-hsss.png"),
  make_fluid("molten-ruridit", fluid_icon_path .. "molten-hssg.png"),
  make_fluid("molten-staballoy", fluid_icon_path .. "dark-blue-spackled-fluid.png"),
  make_fluid("molten-stainless-steel", fluid_icon_path .. "spackled-light-blue-fluid.png"),
  make_fluid("molten-stellite", fluid_icon_path .. "spackled-light-blue-fluid.png"),
  make_fluid("molten-talonite", fluid_icon_path .. "spackled-medium-blue-fluid.png"),
  make_fluid("molten-tantalum", fluid_icon_path .. "spackled-medium-blue-fluid.png"),
  make_fluid("molten-tantalum-carbide", fluid_icon_path .. "spackled-medium-blue-fluid.png"),
  make_fluid("molten-tantalloy-60", fluid_icon_path .. "spackled-medium-blue-fluid.png"),
  make_fluid("molten-tin", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("molten-tungsten", fluid_icon_path .. "dark-gray-spackled-fluid.png"),
  make_fluid("molten-tungsten-carbide", fluid_icon_path .. "molten-hsss.png"),
  make_fluid("molten-tungstensteel", fluid_icon_path .. "molten-tungstensteel.png"),
  make_fluid("molten-ultimet", fluid_icon_path .. "molten-hssg.png"),
  make_fluid("molten-vanadium-gallium", fluid_icon_path .. "soldering-alloy.png"),
  make_fluid("molten-vanadium-steel", fluid_icon_path .. "molten-hssg.png"),
  make_fluid("molten-vibrant-alloy", fluid_icon_path .. "krypton.png"),
  make_fluid("molten-watertight-steel", fluid_icon_path .. "krypton.png"),
  make_fluid("molten-zeron-100", fluid_icon_path .. "molten-hsse.png"),
  make_fluid("naphtha", fluid_icon_path .. "naphtha.png"),
  make_fluid("naquadah-adamantium-solution", fluid_icon_path .. "spackled-purple-fluid.png"),
  make_fluid("naquadah-rich-solution", fluid_icon_path .. "rust-brown-fluid.png"),
  make_fluid("naquadria-rich-solution", fluid_icon_path .. "phenol.png"),
  make_fluid("neon", fluid_icon_path .. "neon.png"),
  make_fluid("nether-air", fluid_icon_path .. "liquid-nether-air.png"),
  make_fluid("nitration-mixture", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("nitric-acid", fluid_icon_path .. "spackled-yellow-fluid.png"),
  make_fluid("nitrochlorobenzene", fluid_icon_path .. "olive-fluid.png"),
  make_fluid("nitrogen", fluid_icon_path .. "nitrogen.png"),
  make_fluid("nitrogen-dioxide", fluid_icon_path .. "nitrogen.png"),
  make_fluid("oxygen", fluid_icon_path .. "oxygen.png"),
  make_fluid("p507", fluid_icon_path .. "medium-green-fluid.png"),
  make_fluid("palladium-rich-ammonia", fluid_icon_path .. "dark-gray-spackled-fluid.png"),
  make_fluid("phenol", fluid_icon_path .. "phenol.png"),
  make_fluid("phosphoric-acid", fluid_icon_path .. "spackled-yellow-fluid.png"),
  make_fluid("phthalic-acid", fluid_icon_path .. "forest-green-fluid.png"),
  make_fluid("platinum-palladium-leachate", fluid_icon_path .. "spackled-silvery-gold-fluid.png"),
  make_fluid("polybenzimidazole", fluid_icon_path .. "black-fluid.png"),
  make_fluid("polyethylene", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("polyphenylene-sulfide", fluid_icon_path .. "methanol.png"),
  make_fluid("polyvinyl-acetate", fluid_icon_path .. "spackled-copper-fluid.png"),
  make_fluid("polyvinyl-chloride", fluid_icon_path .. "spackled-copper-fluid.png"),
  make_fluid("propane", fluid_icon_path .. "propane.png"),
  make_fluid("propene", fluid_icon_path .. "propane.png"),
  make_fluid("ptfe", fluid_icon_path .. "dark-blue-spackled-fluid.png"),
  make_fluid("radon", fluid_icon_path .. "deep-pink-fluid.png"),
  make_fluid("refinery-gas", fluid_icon_path .. "nearly-white-fluid.png"),
  make_fluid("rhodium-sulfate-solution", fluid_icon_path .. "light-orange-fluid.png"),
  make_fluid("rocket-fuel", fluid_icon_path .. "rocket-fuel.png"),
  make_fluid("ruby-juice", fluid_icon_path .. "ruby-juice.png"),
  make_fluid("salt-water", fluid_icon_path .. "deep-blue-fluid.png"),
  make_fluid("silicon-tetrachloride", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("silicone-rubber", fluid_icon_path .. "spackled-gray-fluid.png"),
  make_fluid("sluice-juice", fluid_icon_path .. "spackled-brown-fluid.png"),
  make_fluid("sodium-formate", fluid_icon_path .. "light-pink-fluid.png"),
  make_fluid("sodium-potassium", fluid_icon_path .. "spackled-mint-green-fluid.png"),
  make_fluid("sodium-tungstate", fluid_icon_path .. "light-fuel.png"),
  make_fluid("soldering-alloy", fluid_icon_path .. "soldering-alloy.png"),
  make_fluid("steam-cracked-gas", fluid_icon_path .. "nearly-white-fluid.png"),
  make_fluid("steam-cracked-heavy-fuel", fluid_icon_path .. "heavy-fuel.png"),
  make_fluid("steam-cracked-light-fuel", fluid_icon_path .. "light-fuel.png"),
  make_fluid("steam-cracked-naphtha", fluid_icon_path .. "naphtha.png"),
  make_fluid("sulfur-dioxide", fluid_icon_path .. "dark-muted-yellow-fluid.png"),
  make_fluid("sulfur-trioxide", fluid_icon_path .. "dark-muted-yellow-fluid.png"),
  make_fluid("sulfuric-acid", fluid_icon_path .. "sulfuric-acid.png"),
  make_fluid("sulfuric-copper-solution", fluid_icon_path .. "spackled-medium-blue-fluid.png"),
  make_fluid("sulfuric-gas", fluid_icon_path .. "nearly-white-fluid.png"),
  make_fluid("sulfuric-heavy-fuel", fluid_icon_path .. "heavy-fuel.png"),
  make_fluid("sulfuric-iron-solution", fluid_icon_path .. "biomass.png"),
  make_fluid("sulfuric-light-fuel", fluid_icon_path .. "light-fuel.png"),
  make_fluid("sulfuric-naphtha", fluid_icon_path .. "naphtha.png"),
  make_fluid("sulfuric-nickel-solution", fluid_icon_path .. "rich-green-fluid.png"),
  make_fluid("super-glue", fluid_icon_path .. "ethane.png"),
  make_fluid("tetrafluoroethylene", fluid_icon_path .. "spackled-medium-gray-fluid.png"),
  make_fluid("tetranitromethane", fluid_icon_path .. "deep-blue-fluid.png"),
  make_fluid("titanium-tetrachloride", fluid_icon_path .. "titanium.png"),
  make_fluid("toluene", fluid_icon_path .. "spackled-rich-brown-fluid.png"),
  make_fluid("tritium", fluid_icon_path .. "tritium.png"),
  make_fluid("uranium-hexafluoride", fluid_icon_path .. "rich-green-fluid.png"),
  make_fluid("vinyl-acetate", fluid_icon_path .. "spackled-copper-fluid.png"),
  make_fluid("vinyl-chloride", fluid_icon_path .. "medium-gray-fluid.png"),
  make_fluid("waste-liquid", fluid_icon_path .. "deep-blue-fluid.png"),
  make_fluid("wood-gas", fluid_icon_path .. "rocket-fuel.png"),
  make_fluid("wood-tar", fluid_icon_path .. "wood-tar.png"),
  make_fluid("wood-vinegar", fluid_icon_path .. "sulfuric-acid.png"),
  make_fluid("xenon", fluid_icon_path .. "xenon.png"),
}

data:extend(fluids)