--------------------------------------------------------------------------------
--- FORK MACHINES
--- Missing buildings for EV and IV:
---   * fill tier categories (e.g. the EV fluid solidifier can also do MV/HV/EV recipes)
---   * EV multiblocks whose item existed but could not be placed
---   * IV basic machines (copies of the EV machines, shifted one tier up)
---   * IV multiblocks (GT++ "industrial" machines) from 20-iv-age-entity.lua
--- Sprites in graphics/entity/fork/ are generated by tools/gen_sprites.py.
--------------------------------------------------------------------------------

local TIERS = { "lv", "mv", "hv", "ev", "iv", "luv", "zpm", "uv", "uhv", "uev", "uiv", "umv", "uxv" }
local TIER_INDEX = {}
for i, t in ipairs(TIERS) do TIER_INDEX[t] = i end

local SPRITE_PATH = "__Gregtorio__/graphics/entity/fork/"

local function tier_of(name)
	local t = name:match("^(%a+)%-")
	return t and TIER_INDEX[t] and t or nil
end

local function category_exists(c)
	return data.raw["recipe-category"][c] ~= nil
end

--- Scale energy values like "1.28MW"
local function scale_energy(s, factor)
	local num, unit = s:match("^([%d%.]+)(%a+)$")
	local mult = { W = 1, kW = 1e3, MW = 1e6, GW = 1e9 }
	local watts = tonumber(num) * mult[unit] * factor
	if watts >= 1e9 then return string.format("%.4gGW", watts / 1e9) end
	if watts >= 1e6 then return string.format("%.4gMW", watts / 1e6) end
	return string.format("%.4gkW", watts / 1e3)
end

--- All existing categories "<tier>-<rest>" up to and including max_tier
local function tier_categories(rest, max_tier)
	local out = {}
	for i = 1, TIER_INDEX[max_tier] do
		local c = TIERS[i] .. "-" .. rest
		if category_exists(c) then table.insert(out, c) end
	end
	return out
end

local function add_unique(list, items)
	local seen = {}
	for _, v in pairs(list) do seen[v] = true end
	for _, v in pairs(items) do
		if not seen[v] then table.insert(list, v); seen[v] = true end
	end
	return list
end

--- Fill a machine's categories with all lower (and its own) tiers
local function tier_fill(categories, machine_tier)
	local result = {}
	for _, c in pairs(categories) do
		table.insert(result, c)
		local ct, rest = c:match("^(%a+)%-(.+)$")
		if ct and TIER_INDEX[ct] and TIER_INDEX[ct] <= TIER_INDEX[machine_tier] then
			add_unique(result, tier_categories(rest, machine_tier))
		end
	end
	return add_unique({}, result)
end

--- Graphics set from generated sprites (idle: 1 frame, working: vertical strip)
local function fork_graphics(sprite_name, width_px, height_px, frames)
	return {
		idle_animation = { layers = { {
			filename = SPRITE_PATH .. sprite_name .. "-idle.png",
			width = width_px, height = height_px,
			frame_count = 1, repeat_count = frames, shift = { 0, 0 },
		} } },
		animation = { layers = { {
			filename = SPRITE_PATH .. sprite_name .. "-working.png",
			width = width_px, height = height_px,
			frame_count = frames, line_length = 1, animation_speed = 0.3, shift = { 0, 0 },
		} } },
	}
end

--- New machine as a copy of an existing one
---   def = { name, source, categories, crafting_speed, energy_usage, sprite = {name, frames} | nil,
---           size = {w, h} (only without fluid boxes), keep_fluids = true|false, icon }
local function clone_machine(def)
	local src = data.raw["assembling-machine"][def.source]
	if not src then log("FORK-MACHINE: missing source: " .. def.source) return nil end
	local m = table.deepcopy(src)
	m.name = def.name
	m.minable = { mining_time = 0.5, result = def.name }
	m.crafting_categories = def.categories
	m.crafting_speed = def.crafting_speed or m.crafting_speed
	m.energy_usage = def.energy_usage or m.energy_usage
	m.fast_replaceable_group = def.fast_replaceable_group or m.fast_replaceable_group
	if def.icon then m.icon = def.icon; m.icon_size = 32 end
	if def.keep_fluids == false then
		m.fluid_boxes = nil
		m.fluid_boxes_off_when_no_fluid_recipe = nil
	end
	local w, h
	if def.size then
		w, h = def.size[1], def.size[2]
		m.collision_box = { { -w / 2 + 0.2, -h / 2 + 0.2 }, { w / 2 - 0.2, h / 2 - 0.2 } }
		m.selection_box = { { -w / 2, -h / 2 }, { w / 2, h / 2 } }
	else
		w = src.selection_box[2][1] - src.selection_box[1][1]
		h = src.selection_box[2][2] - src.selection_box[1][2]
	end
	if def.sprite then
		m.graphics_set = fork_graphics(def.sprite[1], w * 32, h * 32, def.sprite[2] or 1)
	end
	data:extend({ m })
	return m
end

--- Point an item at an entity (for items whose place_result was commented out)
local function set_place_result(item_name, entity_name)
	local item = data.raw.item[item_name]
	if not item then log("FORK-MACHINE: missing item: " .. item_name) return end
	item.place_result = entity_name
end



--------------------------------------------------------------------------------
--- 1) FILL TIER CATEGORIES (existing LV-EV machines)
---    e.g. the EV fluid solidifier only had LV recipes, the EV macerator no HV/EV
--------------------------------------------------------------------------------

for name, m in pairs(data.raw["assembling-machine"]) do
	local t = tier_of(name)
	if t and m.crafting_categories and TIER_INDEX[t] <= TIER_INDEX["ev"] then
		m.crafting_categories = tier_fill(m.crafting_categories, t)
	end
end



--- Chemical baths had two fluid INPUTS and no output. All bath recipes need at most
--- 1 fluid in + 1 fluid out (e.g. the platinum line) -> the second port becomes an output (south).
for name, m in pairs(data.raw["assembling-machine"]) do
	local is_bath = false
	for _, c in pairs(m.crafting_categories or {}) do
		if c:match("%-chemical%-bath%-recipes$") then is_bath = true end
	end
	if is_bath and m.fluid_boxes and #m.fluid_boxes == 2 then
		local out = m.fluid_boxes[2]
		out.production_type = "output"
		local h = m.selection_box[2][2]
		for _, pc in pairs(out.pipe_connections) do
			pc.flow_direction = "output"
			pc.direction = defines.direction.south
			pc.position = { pc.position[1], h - 0.5 }
		end
	end
end



--------------------------------------------------------------------------------
--- 2) EV MULTIBLOCKS AND ENDER IO MACHINES (items existed but could not be placed)
--------------------------------------------------------------------------------

--- ALLOY BLAST SMELTER (3x4 like the EBF, same fluid ports)
clone_machine{
	name = "ev-alloy-blast-smelter", source = "ev-electric-blast-furnace",
	categories = tier_categories("alloy-blast-smelter-recipes", "ev"),
	crafting_speed = 8, energy_usage = EU16_EV,
	fast_replaceable_group = "fr-alloy-blast-smelter",
	icon = ICON_PATH .. "alloy-blast-smelter.png",
	sprite = { "ev-alloy-blast-smelter", 1 },
}
set_place_result("ev-alloy-blast-smelter", "ev-alloy-blast-smelter")

--- EXTREME ENTITY CRUSHER
clone_machine{
	name = "ev-extreme-entity-crusher", source = "ev-macerator", keep_fluids = false,
	categories = { "ev-extreme-entity-crusher-recipes" },
	crafting_speed = 1, energy_usage = EU8_EV,
	fast_replaceable_group = "fr-extreme-entity-crusher",
	icon = ICON_PATH .. "extreme-entity-crusher.png",
	sprite = { "ev-extreme-entity-crusher", 1 },
}
set_place_result("ev-extreme-entity-crusher", "ev-extreme-entity-crusher")

--- ENDER IO: Slice'n'Splice, Soul Binder, Powered Spawner
for _, n in pairs({ "slice-n-splice", "soul-binder", "powered-spawner" }) do
	clone_machine{
		name = n, source = "ev-macerator", keep_fluids = false,
		categories = { n .. "-recipes" },
		crafting_speed = 1, energy_usage = EU2_HV,
		fast_replaceable_group = "fr-" .. n,
		icon = ICON_PATH .. n .. ".png",
		sprite = { n, 1 },
	}
	set_place_result(n, n)
end

--- LARGE SIFTER (HV multiblock, 5x3, graphics already exist)
do
	local m = clone_machine{
		name = "hv-large-sifter", source = "ev-macerator", keep_fluids = false, size = { 5, 3 },
		categories = tier_categories("sifter-recipes", "iv"),
		crafting_speed = 4, energy_usage = EU16_HV,
		fast_replaceable_group = "fr-large-sifter",
		icon = ICON_PATH .. "large-sifter.png",
	}
	if m then
		m.graphics_set = {
			idle_animation = { layers = { { filename = "__Gregtorio__/graphics/entity/large-sifter/large-sifter-idle.png",
				width = 160, height = 96, frame_count = 1, shift = { 0, 0 } } } },
			animation = { layers = { { filename = "__Gregtorio__/graphics/entity/large-sifter/large-sifter-working.png",
				width = 160, height = 96, frame_count = 1, shift = { 0, 0 } } } },
		}
	end
	set_place_result("hv-large-sifter", "hv-large-sifter")
end



--------------------------------------------------------------------------------
--- 3) IV BASIC MACHINES
---    Copy of the EV machine: double speed, double power draw, IV categories added,
---    recipe = EV recipe with every tiered component shifted one tier up.
--------------------------------------------------------------------------------

--- Shift an ingredient one tier up (ev-motor -> iv-motor, hv-energy-hatch -> ev-energy-hatch, ...)
--- Special cases per target tier (cables and heating coils carry no tier in their name)
local SPECIAL_SHIFT = {
	iv = {
		["aluminium-cable"]     = "tungsten-cable",
		["platinum-cable"]      = "tungsten-cable",
		["cupronickel-coil-block"] = "kanthal-coil-block",
		["kanthal-coil-block"]  = "nichrome-coil-block",
		["nichrome-coil-block"] = "rtm-alloy-coil-block",
	},
	luv = {
		["tungsten-cable"]      = "yttrium-barium-cuprate-cable",
		["kanthal-coil-block"]  = "nichrome-coil-block",
		["nichrome-coil-block"] = "rtm-alloy-coil-block",
		["rtm-alloy-coil-block"] = "hssg-coil-block",
		["luv-circuit"]         = "luv-circuit",   -- ZPM circuits do not exist yet at LuV
	},
	--- ZPM machines (126-fork-zpm.lua): naquadah is the ZPM cable and coil material in GT
	zpm = {
		["yttrium-barium-cuprate-cable"] = "naquadah-cable",
		["rtm-alloy-coil-block"] = "hssg-coil-block",
		["hssg-coil-block"]     = "naquadah-coil-block",
	},
	--- UV machines (127-fork-uv.lua): naquadah alloy cable, trinium coils
	uv = {
		["naquadah-cable"]      = "naquadah-alloy-cable",
		["hssg-coil-block"]     = "naquadah-coil-block",
		["naquadah-coil-block"] = "trinium-coil-block",
	},
	--- UHV machines (128-fork-uhv.lua): tritanium cable, tritanium coils
	uhv = {
		["naquadah-alloy-cable"] = "tritanium-cable",
		["naquadah-coil-block"] = "trinium-coil-block",
		["trinium-coil-block"]  = "tritanium-coil-block",
	},
}
local function item_exists(n)
	for t, _ in pairs(defines.prototypes.item) do
		if data.raw[t] and data.raw[t][n] then return true end
	end
	return false
end
local function shift_name(n, to_tier)
	local special = SPECIAL_SHIFT[to_tier] or {}
	if special[n] and item_exists(special[n]) then return special[n] end
	local t, rest = n:match("^(%a+)%-(.+)$")
	if t and TIER_INDEX[t] and TIERS[TIER_INDEX[t] + 1] then
		local shifted = TIERS[TIER_INDEX[t] + 1] .. "-" .. rest
		if item_exists(shifted) then return shifted end
	end
	return n
end
local function shift_list(list, to_tier)
	local out = {}
	for _, i in pairs(list or {}) do
		local c = table.deepcopy(i)
		if c.type ~= "fluid" then c.name = shift_name(c.name, to_tier) end
		table.insert(out, c)
	end
	return out
end

--- Machines that get generated sprites (from GT textures)
IV_BASIC_MACHINES = {
	"wiremill", "bending-machine", "extruder", "rock-crusher", "lathe", "macerator", "centrifuge",
	"air-collector", "extractor", "electrolyzer", "assembling-machine", "cutting-machine",
	"canning-machine", "mixer", "ore-washer", "laser-engraver", "fluid-solidifier", "chemical-bath",
	"polarizer", "circuit-assembler", "autoclave", "alloy-smelter", "compressor",
}
--- Multiblocks that come as an upgrade of the EV version (same graphics as EV)
IV_UPGRADE_MACHINES = {
	"electric-blast-furnace", "vacuum-freezer", "large-chemical-reactor", "microverse-projector",
	"tall-distillation-tower", "short-distillation-tower", "implosion-compressor", "cracker",
	"multismelter", "pyrolyse-oven", "greenhouse", "drilling-rig", "alloy-blast-smelter",
}

--- Create a machine one tier up (entity, item, recipe). Global so 110-fork-luv.lua can use it.
function fork_make_tier_machine(base, from_tier, to_tier, sprite_frames, unlock_tech)
	local src_name, new_name = from_tier .. "-" .. base, to_tier .. "-" .. base
	local src = data.raw["assembling-machine"][src_name]
	if not src then log("FORK-MACHINE: no source machine " .. src_name) return end
	local categories = table.deepcopy(src.crafting_categories)
	local extra = {}
	for _, c in pairs(categories) do
		local ct, rest = c:match("^(%a+)%-(.+)$")
		if ct and TIER_INDEX[ct] then add_unique(extra, tier_categories(rest, to_tier)) end
	end
	categories = add_unique(categories, extra)

	local icon = sprite_frames and ("__Gregtorio__/graphics/icons/fork/" .. new_name .. ".png") or nil
	clone_machine{
		name = new_name, source = src_name, categories = categories,
		crafting_speed = src.crafting_speed * 2,
		energy_usage = scale_energy(src.energy_usage, 2),
		sprite = sprite_frames and { new_name, sprite_frames } or nil,
		icon = icon,
	}

	--- Item
	local src_item = data.raw.item[src_name]
	local item = table.deepcopy(src_item)
	item.name = new_name
	item.place_result = new_name
	item.order = (src_item.order or "") .. "-" .. to_tier
	local sg = item.subgroup or ""
	if sg:match("age%-production%-machine$") then item.subgroup = to_tier .. "-age-production-machine" end
	if sg:match("age%-multiblocks$") then item.subgroup = "subgroup-" .. to_tier .. "-age-multiblocks" end
	if icon then item.icon = icon; item.icon_size = 32 end
	data:extend({ item })

	--- Recipe
	local src_recipe = data.raw.recipe[src_name]
	local r = table.deepcopy(src_recipe)
	r.name = new_name
	r.enabled = false
	r.ingredients = shift_list(src_recipe.ingredients, to_tier)
	r.results = shift_list(src_recipe.results, to_tier)
	for _, res in pairs(r.results) do if res.name == src_name then res.name = new_name end end
	if r.main_product then r.main_product = new_name end
	--- Upgrade multiblocks: the previous version goes in, not the new version itself
	for _, ing in pairs(r.ingredients) do if ing.name == new_name then ing.name = src_name end end
	data:extend({ r })
	if unlock_tech then fork_add_unlock(unlock_tech, new_name) end
end

for _, t in pairs({ "iv", "luv", "zpm" }) do
	if not data.raw["item-subgroup"][t .. "-age-production-machine"] then
		data:extend({ { type = "item-subgroup", name = t .. "-age-production-machine", group = "production", order = "i-z-" .. t } })
	end
end

for _, base in pairs(IV_BASIC_MACHINES) do fork_make_tier_machine(base, "ev", "iv", 6, "iv-machines") end
for _, base in pairs(IV_UPGRADE_MACHINES) do fork_make_tier_machine(base, "ev", "iv", nil, "iv-machines") end



--------------------------------------------------------------------------------
--- 4) IV MULTIBLOCKS (GT++ industrial machines), items from 20-iv-age-entity.lua
---    Process all recipes of their machine family up to IV, twice as fast as IV.
--------------------------------------------------------------------------------

local IV_MULTIBLOCKS = {
	-- item/entity                          source (fluid ports)   category family
	{ "iv-industrial-maceration-stack",     "ev-macerator",        { "macerator-recipes" } },
	{ "iv-industrial-wire-factory",         "ev-wiremill",         { "wiremill-recipes" } },
	{ "iv-industrial-material-press",       "ev-bending-machine",  { "bending-machine-recipes" } },
	{ "iv-large-electric-compressor",       "ev-compressor",       { "compressor-recipes" } },
	{ "iv-magnetic-flux-exhibiter",         "ev-polarizer",        { "polarizer-recipes" } },
	{ "iv-fluid-shaper",                    "ev-fluid-solidifier", { "fluid-solidifier-recipes" } },
	{ "iv-industrial-cutting-factory",      "ev-cutting-machine",  { "cutting-machine-recipes" } },
	{ "iv-chemical-bath-plant",             "ev-chemical-bath",    { "chemical-bath-recipes" } },
	{ "iv-industrial-electrolyzer",         "ev-electrolyzer",     { "electrolyzer-recipes" } },
	{ "iv-industrial-precision-lathe",      "ev-lathe",            { "lathe-recipes" } },
	{ "iv-large-extractor",                 "ev-extractor",        { "extractor-recipes" } },
	{ "iv-hyper-intensity-laser-engraver",  "ev-laser-engraver",   { "laser-engraver-recipes" } },
	{ "iv-industrial-extrusion-machine",    "ev-extruder",         { "extruder-recipes" } },
	{ "iv-industrial-centrifuge",           "ev-centrifuge",       { "centrifuge-recipes" } },
	{ "iv-industrial-mixer",                "ev-mixer",            { "mixer-recipes" } },
	{ "iv-turbocan-pro",                    "ev-canning-machine",  { "canning-machine-recipes" } },
	{ "iv-zyngen",                          "ev-alloy-smelter",    { "alloy-smelter-recipes" } },
}

for _, mb in pairs(IV_MULTIBLOCKS) do
	local name, source, families = mb[1], mb[2], mb[3]
	if data.raw.item[name] then
		local categories = {}
		for _, fam in pairs(families) do add_unique(categories, tier_categories(fam, "iv")) end
		local src = data.raw["assembling-machine"][source]
		clone_machine{
			name = name, source = source, categories = categories,
			crafting_speed = 32,
			energy_usage = src and scale_energy(src.energy_usage, 4) or EU16_IV,
			fast_replaceable_group = "fr-" .. name,
			icon = data.raw.item[name].icon,
			sprite = { name, 1 },
		}
		set_place_result(name, name)
	else
		log("FORK-MACHINE: missing IV multiblock item: " .. name)
	end
end

--- Upstream bugs in the IV multiblock recipes
do
	--- The wire factory needed itself instead of its controller
	local r = data.raw.recipe["iv-industrial-wire-factory"]
	if r then
		for _, ing in pairs(r.ingredients) do
			if ing.name == "iv-industrial-wire-factory" then ing.name = "industrial-wire-factory-controller" end
		end
	end
	--- The precision lathe had the electrolyzer's icon
	local it = data.raw.item["iv-industrial-precision-lathe"]
	if it then it.icon = ICON_PATH .. "industrial-precision-lathe.png" end
	--- Zyngen had the industrial mixer's icon
	local zy = data.raw.item["iv-zyngen"]
	if zy then zy.icon = ICON_PATH .. "zyngen.png" end
end
