--------------------------------------------------------------------------------
--- FORK MACHINES
--- Missing buildings for EV and IV:
---   * fill tier categories (e.g. the EV fluid solidifier can also do MV/HV/EV recipes)
---   * EV multiblocks whose item existed but could not be placed
---   * IV basic machines (copies of the EV machines, shifted one tier up)
---   * IV multiblocks (GT++ "industrial" machines) from 20-iv-age-entity.lua
--- Sprites in graphics/entity/fork/ are generated by tools/gen_sprites.py.
--------------------------------------------------------------------------------

local TIERS = { "lv", "mv", "hv", "ev", "iv", "luv", "zpm", "uv", "uhv", "uev", "uiv", "umv", "uxv", "max" }
local TIER_INDEX = {}
for i, t in ipairs(TIERS) do TIER_INDEX[t] = i end

local SPRITE_PATH = "__gregtorio-continued__/graphics/entity/fork/"

local function tier_of(name)
	local t = name:match("^(%a+)%-")
	return t and TIER_INDEX[t] and t or nil
end

local function category_exists(c)
	return data.raw["recipe-category"][c] ~= nil
end

--- Scale energy values like "1.28MW"
local function scale_energy(s, factor)
	local num, unit = s:match("^([%d%.]+)(%a+)$")
	local mult = { W = 1, kW = 1e3, MW = 1e6, GW = 1e9 }
	local watts = tonumber(num) * mult[unit] * factor
	if watts >= 1e9 then return string.format("%.4gGW", watts / 1e9) end
	if watts >= 1e6 then return string.format("%.4gMW", watts / 1e6) end
	return string.format("%.4gkW", watts / 1e3)
end

--- All existing categories "<tier>-<rest>" up to and including max_tier
local function tier_categories(rest, max_tier)
	local out = {}
	for i = 1, TIER_INDEX[max_tier] do
		local c = TIERS[i] .. "-" .. rest
		if category_exists(c) then table.insert(out, c) end
	end
	return out
end

local function add_unique(list, items)
	local seen = {}
	for _, v in pairs(list) do seen[v] = true end
	for _, v in pairs(items) do
		if not seen[v] then table.insert(list, v); seen[v] = true end
	end
	return list
end

--- Fill a machine's categories with all lower (and its own) tiers
local function tier_fill(categories, machine_tier)
	local result = {}
	for _, c in pairs(categories) do
		table.insert(result, c)
		local ct, rest = c:match("^(%a+)%-(.+)$")
		if ct and TIER_INDEX[ct] and TIER_INDEX[ct] <= TIER_INDEX[machine_tier] then
			add_unique(result, tier_categories(rest, machine_tier))
		end
	end
	return add_unique({}, result)
end

--- Graphics set from generated sprites (idle: 1 frame, working: vertical strip)
local function fork_graphics(sprite_name, width_px, height_px, frames)
	return {
		idle_animation = { layers = { {
			filename = SPRITE_PATH .. sprite_name .. "-idle.png",
			width = width_px, height = height_px,
			frame_count = 1, repeat_count = frames, shift = { 0, 0 },
		} } },
		animation = { layers = { {
			filename = SPRITE_PATH .. sprite_name .. "-working.png",
			width = width_px, height = height_px,
			frame_count = frames, line_length = 1, animation_speed = 0.3, shift = { 0, 0 },
		} } },
	}
end

--- New machine as a copy of an existing one
---   def = { name, source, categories, crafting_speed, energy_usage, sprite = {name, frames} | nil,
---           size = {w, h} (only without fluid boxes), keep_fluids = true|false, icon }
local function clone_machine(def)
	local src = data.raw["assembling-machine"][def.source]
	if not src then log("FORK-MACHINE: missing source: " .. def.source) return nil end
	local m = table.deepcopy(src)
	m.name = def.name
	m.minable = { mining_time = 0.5, result = def.name }
	m.crafting_categories = def.categories
	m.crafting_speed = def.crafting_speed or m.crafting_speed
	m.energy_usage = def.energy_usage or m.energy_usage
	m.fast_replaceable_group = def.fast_replaceable_group or m.fast_replaceable_group
	if def.icon then m.icon = def.icon; m.icon_size = 32 end
	if def.keep_fluids == false then
		m.fluid_boxes = nil
		m.fluid_boxes_off_when_no_fluid_recipe = nil
	end
	local w, h
	if def.size then
		w, h = def.size[1], def.size[2]
		m.collision_box = { { -w / 2 + 0.2, -h / 2 + 0.2 }, { w / 2 - 0.2, h / 2 - 0.2 } }
		m.selection_box = { { -w / 2, -h / 2 }, { w / 2, h / 2 } }
	else
		w = src.selection_box[2][1] - src.selection_box[1][1]
		h = src.selection_box[2][2] - src.selection_box[1][2]
	end
	if def.sprite then
		m.graphics_set = fork_graphics(def.sprite[1], w * 32, h * 32, def.sprite[2] or 1)
	end
	data:extend({ m })
	return m
end

--- Point an item at an entity (for items whose place_result was commented out)
local function set_place_result(item_name, entity_name)
	local item = data.raw.item[item_name]
	if not item then log("FORK-MACHINE: missing item: " .. item_name) return end
	item.place_result = entity_name
end



--------------------------------------------------------------------------------
--- 1) FILL TIER CATEGORIES (existing LV-EV machines)
---    e.g. the EV fluid solidifier only had LV recipes, the EV macerator no HV/EV
--------------------------------------------------------------------------------

for name, m in pairs(data.raw["assembling-machine"]) do
	local t = tier_of(name)
	if t and m.crafting_categories and TIER_INDEX[t] <= TIER_INDEX["ev"] then
		m.crafting_categories = tier_fill(m.crafting_categories, t)
	end
end



--- Chemical baths had two fluid INPUTS and no output. All bath recipes need at most
--- 1 fluid in + 1 fluid out (e.g. the platinum line) -> the second port becomes an output (south).
for name, m in pairs(data.raw["assembling-machine"]) do
	local is_bath = false
	for _, c in pairs(m.crafting_categories or {}) do
		if c:match("%-chemical%-bath%-recipes$") then is_bath = true end
	end
	if is_bath and m.fluid_boxes and #m.fluid_boxes == 2 then
		local out = m.fluid_boxes[2]
		out.production_type = "output"
		local h = m.selection_box[2][2]
		for _, pc in pairs(out.pipe_connections) do
			pc.flow_direction = "output"
			pc.direction = defines.direction.south
			pc.position = { pc.position[1], h - 0.5 }
		end
	end
end



--------------------------------------------------------------------------------
--- 2) EV MULTIBLOCKS AND ENDER IO MACHINES (items existed but could not be placed)
--------------------------------------------------------------------------------

--- ALLOY BLAST SMELTER (3x4 like the EBF, same fluid ports)
clone_machine{
	name = "ev-alloy-blast-smelter", source = "ev-electric-blast-furnace",
	categories = tier_categories("alloy-blast-smelter-recipes", "ev"),
	crafting_speed = 8, energy_usage = EU16_EV,
	fast_replaceable_group = "fr-alloy-blast-smelter",
	icon = ICON_PATH .. "alloy-blast-smelter.png",
	sprite = { "ev-alloy-blast-smelter", 1 },
}
set_place_result("ev-alloy-blast-smelter", "ev-alloy-blast-smelter")

--- EXTREME ENTITY CRUSHER
clone_machine{
	name = "ev-extreme-entity-crusher", source = "ev-macerator", keep_fluids = false,
	categories = { "ev-extreme-entity-crusher-recipes" },
	crafting_speed = 1, energy_usage = EU8_EV,
	fast_replaceable_group = "fr-extreme-entity-crusher",
	icon = ICON_PATH .. "extreme-entity-crusher.png",
	sprite = { "ev-extreme-entity-crusher", 1 },
}
set_place_result("ev-extreme-entity-crusher", "ev-extreme-entity-crusher")

--- ENDER IO: Slice'n'Splice, Soul Binder, Powered Spawner
for _, n in pairs({ "slice-n-splice", "soul-binder", "powered-spawner" }) do
	clone_machine{
		name = n, source = "ev-macerator", keep_fluids = false,
		categories = { n .. "-recipes" },
		crafting_speed = 1, energy_usage = EU2_HV,
		fast_replaceable_group = "fr-" .. n,
		icon = ICON_PATH .. n .. ".png",
		sprite = { n, 1 },
	}
	set_place_result(n, n)
end

--- LARGE SIFTER (HV multiblock, 5x3, graphics already exist)
do
	local m = clone_machine{
		name = "hv-large-sifter", source = "ev-macerator", keep_fluids = false, size = { 5, 3 },
		categories = tier_categories("sifter-recipes", "iv"),
		crafting_speed = 4, energy_usage = EU16_HV,
		fast_replaceable_group = "fr-large-sifter",
		icon = ICON_PATH .. "large-sifter.png",
	}
	if m then
		m.graphics_set = {
			idle_animation = { layers = { { filename = "__gregtorio-continued__/graphics/entity/large-sifter/large-sifter-idle.png",
				width = 160, height = 96, frame_count = 1, shift = { 0, 0 } } } },
			animation = { layers = { { filename = "__gregtorio-continued__/graphics/entity/large-sifter/large-sifter-working.png",
				width = 160, height = 96, frame_count = 1, shift = { 0, 0 } } } },
		}
	end
	set_place_result("hv-large-sifter", "hv-large-sifter")
end



--------------------------------------------------------------------------------
--- 2b) FORGE HAMMER, LV TO EV (issue #170)
---    GT New Horizons has the Forge Hammer from LV up ("Basic Forge Hammer", LoaderMetaTileEntities.java:5388), on the
---    recipe map of the Steam Forge Hammer (hammerRecipes); upstream had only the steam one. The electric ones run the
---    steam hammer's category lv-forge-hammer-recipes (its plates are GT's already: 3 ingots -> 2 plates in the time of
---    the material's mass), share its fast replace group (one can be placed over the steam hammer) and are built as in GT
---    (MTERecipeLoader.java registerForgeHammer, "WPW", "CMC", "WAW": 4 cables, a piston, 2 circuits, the hull, an
---    anvil). LV with the LV piston (technology Bending Machine), MV to EV with the machines of their tier. Sprites:
---    tools/gen_sprites.py (forge_hammer_lv_mv: the steam hammer's picture in the LV and MV casing); IV to MAX follow
---    from IV_BASIC_MACHINES below.
--------------------------------------------------------------------------------

do
	local HAMMERS = {
		--  tier  path                 energy    speed  cable             circuit               tech
		{ "lv", "lv-forge-hammer", EU16_LV, 1, "tin-cable",       "electronic-circuit", "bending-machine" },
		{ "mv", "mv-forge-hammer", EU16_MV, 2, "copper-cable",    "advanced-circuit",   "mv-machines" },
		{ "hv", "mv-forge-hammer", EU16_HV, 4, "gold-cable",      "processing-unit",    "hv-machines" },
		{ "ev", "mv-forge-hammer", EU16_EV, 8, "aluminium-cable", "ev-circuit",         "ev-machines" },
	}
	for _, h in ipairs(HAMMERS) do
		local t, path, energy, speed, cable, circuit, tech = table.unpack(h)
		local name = t .. "-forge-hammer"
		make_electric_machine(name, name, path, { "lv-forge-hammer-recipes" }, "fr-forge-hammer", energy, speed, 5, 0.5, 3, 3)
		create_item{
			name = name,
			subgroup = t .. "-age-production-machine",
			ingredients = {
				{ type = "item", name = cable, amount = 4 },
				{ type = "item", name = t .. "-piston", amount = 1 },
				{ type = "item", name = circuit, amount = 2 },
				{ type = "item", name = t .. "-machine-hull", amount = 1 },
				{ type = "item", name = "anvil", amount = 1 },
			},
			place_result = name,
			stack_size = 10,
		}
		fork_add_unlock(tech, name)
	end
	data.raw["assembling-machine"]["lv-forge-hammer"].next_upgrade = "mv-forge-hammer"
	data.raw["assembling-machine"]["mv-forge-hammer"].next_upgrade = "hv-forge-hammer"
	data.raw["assembling-machine"]["hv-forge-hammer"].next_upgrade = "ev-forge-hammer"

	--- GT's hammer recipes of the items Gregtorio has (ForgeHammerRecipes.java: gravel -> sand, glass -> glass dust,
	--- brick block -> 3 bricks, 10 ticks each); the steam hammer runs them too, as GT's does
	for _, r in pairs({ { "sand-forge-hammer", "gravel", 1, "sand", 1 }, { "glass-dust-forge-hammer", "glass", 1, "glass-dust", 1 },
		{ "brick-forge-hammer", "brick-block", 1, "brick", 3 } }) do
		create_recipe{
			recipe_name = r[1],
			category = "lv-forge-hammer-recipes",
			energy_required = 0.5,
			ingredients = { { type = "item", name = r[2], amount = r[3] } },
			results = { { type = "item", name = r[4], amount = r[5] } },
		}
		fork_add_unlock("steam-forge-hammer", r[1])
	end
end



--------------------------------------------------------------------------------
--- 2c) ARC FURNACE, LV TO EV (issue #171)
---    GT New Horizons has the Arc Furnace from LV up ("Basic Arc Furnace", LoaderMetaTileEntities.java:7293, recipe map
---    arcFurnaceRecipes, which no other basic machine runs); upstream had none. Its recipe of Gregtorio's materials:
---    annealed copper, copper arc-smelted with oxygen (MaterialsInit.java: setArcSmeltingIntoWithGas Oxygen ->
---    AnnealedCopper; GTRecipeRegistrator.registerReverseArcSmelting: max(16, mass) ticks and litres, LV), which upstream
---    ran in the MV electric blast furnace with exactly these numbers: the recipe moves to the arc furnace, its name and
---    technology (Integrated Circuits) kept. GT's recycling of every part into ingots is not built (#171). Machine recipe as
---    GT's (MTERecipeLoader.java registerArcFurnace: "WGW", "CMC", "PPP": two 4x cables, a graphite cell, 2 circuits, the
---    hull, 3 plates of the tier; here 8 cables, as Gregtorio has no 4x tier cables, and graphite); one oxygen input. LV
---    with Integrated Circuits (the annealed copper), MV to EV with the machines of their tier. Sprites: tools/gen_sprites.py (arc_furnace_lv_mv); IV to MAX through IV_BASIC_MACHINES.
--------------------------------------------------------------------------------

recipe_category_and_subgroup("lv-arc-furnace-recipes")
do
	local ARCS = {
		--  tier  path               energy    speed  cable             circuit               plate                    tech
		{ "lv", "lv-arc-furnace", EU30_LV, 1, "tin-cable",       "electronic-circuit", "steel-plate",           "integrated-circuits" },
		{ "mv", "mv-arc-furnace", EU30_MV, 2, "copper-cable",    "advanced-circuit",   "aluminium-plate",       "mv-machines" },
		{ "hv", "mv-arc-furnace", EU30_HV, 4, "gold-cable",      "processing-unit",    "stainless-steel-plate", "hv-machines" },
		{ "ev", "mv-arc-furnace", EU30_EV, 8, "aluminium-cable", "ev-circuit",         "titanium-plate",        "ev-machines" },
	}
	for _, a in ipairs(ARCS) do
		local t, path, energy, speed, cable, circuit, plate, tech = table.unpack(a)
		local name = t .. "-arc-furnace"
		make_electric_machine(name, name, path, { "lv-arc-furnace-recipes" }, "fr-arc-furnace", energy, speed, 1, 0.5, 3, 3, {
			fluid_port(-1, -1, "input", defines.direction.north),
		})
		create_item{
			name = name,
			subgroup = t .. "-age-production-machine",
			ingredients = {
				{ type = "item", name = cable, amount = 8 },
				{ type = "item", name = "graphite", amount = 1 },
				{ type = "item", name = circuit, amount = 2 },
				{ type = "item", name = t .. "-machine-hull", amount = 1 },
				{ type = "item", name = plate, amount = 3 },
			},
			place_result = name,
			stack_size = 10,
		}
		fork_add_unlock(tech, name)
	end
	data.raw["assembling-machine"]["lv-arc-furnace"].next_upgrade = "mv-arc-furnace"
	data.raw["assembling-machine"]["mv-arc-furnace"].next_upgrade = "hv-arc-furnace"
	data.raw["assembling-machine"]["hv-arc-furnace"].next_upgrade = "ev-arc-furnace"

	local r = data.raw.recipe["annealed-copper-ingot"]
	r.category = "lv-arc-furnace-recipes"
	r.subgroup = "subgroup-lv-arc-furnace-recipes"
end



--------------------------------------------------------------------------------
--- 2d) FORMING PRESS, LV TO EV (issue #173)
---    GT New Horizons has the Forming Press from LV up ("Basic Forming Press", LoaderMetaTileEntities.java:5229, recipe
---    map formingPressRecipes, which no other basic machine runs); upstream had none. GTNH presses AE2's printed circuits
---    in it (FormingPressRecipes.java: a plate or crystal and the inscriber press, which is not used up, 10 s at LV):
---    Gregtorio's four printed circuit recipes have exactly these inputs and times but ran in the LV circuit assembler;
---    they move to the forming press, their names and technologies kept (the press goes back to the output as before).
---    Machine recipe as GT's (MTERecipeLoader.java registerFormingPress, "WPW", "CMC", "WPW": 4 cables, 2 pistons, 2
---    circuits, the hull). LV with every technology that unlocks a printed circuit, MV to EV with the machines of their
---    tier. Sprites: tools/gen_sprites.py (forming_press_lv_mv); IV to MAX through IV_BASIC_MACHINES.
--------------------------------------------------------------------------------

recipe_category_and_subgroup("lv-forming-press-recipes")
do
	local PRINTED = { "printed-silicon", "printed-logic-circuit", "printed-calculation-circuit", "printed-engineering-circuit" }
	local lv_techs = {}
	for name, tech in pairs(data.raw.technology) do
		for _, e in pairs(tech.effects or {}) do
			for _, r in pairs(PRINTED) do
				if e.type == "unlock-recipe" and e.recipe == r then lv_techs[name] = true end
			end
		end
	end
	local PRESSES = {
		--  tier  path                 energy    speed  cable             circuit
		{ "lv", "lv-forming-press", EU16_LV, 1, "tin-cable",       "electronic-circuit" },
		{ "mv", "mv-forming-press", EU16_MV, 2, "copper-cable",    "advanced-circuit" },
		{ "hv", "mv-forming-press", EU16_HV, 4, "gold-cable",      "processing-unit" },
		{ "ev", "mv-forming-press", EU16_EV, 8, "aluminium-cable", "ev-circuit" },
	}
	for _, a in ipairs(PRESSES) do
		local t, path, energy, speed, cable, circuit = table.unpack(a)
		local name = t .. "-forming-press"
		make_electric_machine(name, name, path, { "lv-forming-press-recipes" }, "fr-forming-press", energy, speed, 1, 0.5, 3, 3)
		create_item{
			name = name,
			subgroup = t .. "-age-production-machine",
			ingredients = {
				{ type = "item", name = cable, amount = 4 },
				{ type = "item", name = t .. "-piston", amount = 2 },
				{ type = "item", name = circuit, amount = 2 },
				{ type = "item", name = t .. "-machine-hull", amount = 1 },
			},
			place_result = name,
			stack_size = 10,
		}
		if t == "lv" then
			local names = {}
			for tech, _ in pairs(lv_techs) do names[#names + 1] = tech end
			table.sort(names)
			for _, tech in ipairs(names) do fork_add_unlock(tech, name) end
		else
			fork_add_unlock(t .. "-machines", name)
		end
	end
	data.raw["assembling-machine"]["lv-forming-press"].next_upgrade = "mv-forming-press"
	data.raw["assembling-machine"]["mv-forming-press"].next_upgrade = "hv-forming-press"
	data.raw["assembling-machine"]["hv-forming-press"].next_upgrade = "ev-forming-press"

	for _, n in pairs(PRINTED) do
		local r = data.raw.recipe[n]
		r.category = "lv-forming-press-recipes"
		r.subgroup = "subgroup-lv-forming-press-recipes"
	end
end



--------------------------------------------------------------------------------
--- 2e) ELECTRIC FURNACE, LV TO EV (issue #174)
---    GT New Horizons has the Electric Furnace from LV up ("Basic Electric Furnace", LoaderMetaTileEntities.java:4319),
---    which runs the smelting recipes (furnaceRecipes); upstream smelted only in the burner furnaces (stone, iron and
---    steel furnace) and the Multi Smelter. The electric furnaces run the category smelting. Machine recipe as GT's
---    (MTERecipeLoader.java registerElectricFurnace, "ECE", "CMC", "WCW": 2 circuits, 4 double heating wires of the tier
---    (GTModHandler COIL_HEATING: copper, cupronickel, kanthal, nichrome), the hull, 2 cables; here 8 single wires, as
---    Gregtorio has no double wires). Power EU8, the lowest class Gregtorio has (GT smelts at 4 EU/t). LV with Wiremill (its copper wire), MV to EV with the machines of their tier.
---    Sprites: tools/gen_sprites.py (electric_furnace_lv_mv); IV to MAX through IV_BASIC_MACHINES.
--------------------------------------------------------------------------------

do
	local FURNACES = {
		--  tier  path                    energy    speed  cable             circuit               coil                 tech
		{ "lv", "lv-electric-furnace", EU8_LV, 1, "tin-cable",       "electronic-circuit", "copper-wire",       "wiremill" },
		{ "mv", "mv-electric-furnace", EU8_MV, 2, "copper-cable",    "advanced-circuit",   "cupronickel-wire",  "mv-machines" },
		{ "hv", "mv-electric-furnace", EU8_HV, 4, "gold-cable",      "processing-unit",    "kanthal-wire",      "hv-machines" },
		{ "ev", "mv-electric-furnace", EU8_EV, 8, "aluminium-cable", "ev-circuit",         "nichrome-wire",     "ev-machines" },
	}
	for _, a in ipairs(FURNACES) do
		local t, path, energy, speed, cable, circuit, coil, tech = table.unpack(a)
		local name = t .. "-electric-furnace"
		make_electric_machine(name, name, path, { "smelting" }, "fr-electric-furnace", energy, speed, 1, 0.5, 3, 3)
		create_item{
			name = name,
			subgroup = t .. "-age-production-machine",
			ingredients = {
				{ type = "item", name = circuit, amount = 2 },
				{ type = "item", name = coil, amount = 8 },
				{ type = "item", name = t .. "-machine-hull", amount = 1 },
				{ type = "item", name = cable, amount = 2 },
			},
			place_result = name,
			stack_size = 10,
		}
		fork_add_unlock(tech, name)
	end
	data.raw["assembling-machine"]["lv-electric-furnace"].next_upgrade = "mv-electric-furnace"
	data.raw["assembling-machine"]["mv-electric-furnace"].next_upgrade = "hv-electric-furnace"
	data.raw["assembling-machine"]["hv-electric-furnace"].next_upgrade = "ev-electric-furnace"
end



--------------------------------------------------------------------------------
--- 3) IV BASIC MACHINES
---    Copy of the EV machine: double speed, double power draw, IV categories added,
---    recipe = EV recipe with every tiered component shifted one tier up.
--------------------------------------------------------------------------------

--- Shift an ingredient one tier up (ev-motor -> iv-motor, hv-energy-hatch -> ev-energy-hatch, ...)
--- Special cases per target tier (cables and heating coils carry no tier in their name)
local SPECIAL_SHIFT = {
	iv = {
		["aluminium-cable"]     = "tungsten-cable",
		["platinum-cable"]      = "tungsten-cable",
		["cupronickel-coil-block"] = "kanthal-coil-block",
		["kanthal-coil-block"]  = "nichrome-coil-block",
		["nichrome-coil-block"] = "rtm-alloy-coil-block",
	},
	luv = {
		["tungsten-cable"]      = "yttrium-barium-cuprate-cable",
		["kanthal-coil-block"]  = "nichrome-coil-block",
		["nichrome-coil-block"] = "rtm-alloy-coil-block",
		["rtm-alloy-coil-block"] = "hssg-coil-block",
		["luv-circuit"]         = "luv-circuit",   -- ZPM circuits do not exist yet at LuV
	},
	--- ZPM machines (126-fork-zpm.lua): naquadah is the ZPM cable and coil material in GT
	zpm = {
		["yttrium-barium-cuprate-cable"] = "naquadah-cable",
		["rtm-alloy-coil-block"] = "hssg-coil-block",
		["hssg-coil-block"]     = "naquadah-coil-block",
	},
	--- UV machines (127-fork-uv.lua): naquadah alloy cable, trinium coils
	uv = {
		["naquadah-cable"]      = "naquadah-alloy-cable",
		["hssg-coil-block"]     = "naquadah-coil-block",
		["naquadah-coil-block"] = "trinium-coil-block",
	},
	--- UHV machines (128-fork-uhv.lua): tritanium cable, tritanium coils
	uhv = {
		["naquadah-alloy-cable"] = "tritanium-cable",
		["naquadah-coil-block"] = "trinium-coil-block",
		["trinium-coil-block"]  = "tritanium-coil-block",
	},
	--- UEV machines (131-fork-uev.lua): draconium cable, awakened draconium coils
	uev = {
		["tritanium-cable"]      = "draconium-cable",
		["trinium-coil-block"]   = "tritanium-coil-block",
		["tritanium-coil-block"] = "awakened-draconium-coil-block",
	},
	--- UIV machines (132-fork-uiv.lua): nether star cable, infinity coils
	uiv = {
		["draconium-cable"]      = "nether-star-cable",
		["tritanium-coil-block"] = "awakened-draconium-coil-block",
		["awakened-draconium-coil-block"] = "infinity-coil-block",
	},
	--- UMV machines (133-fork-umv.lua): spacetime cable, spacetime coils
	umv = {
		["nether-star-cable"]    = "spacetime-cable",
		["awakened-draconium-coil-block"] = "infinity-coil-block",
		["infinity-coil-block"]  = "spacetime-coil-block",
	},
	--- UXV machines (134-fork-uxv.lua): universium cable, eternal coils
	uxv = {
		["spacetime-cable"]      = "universium-cable",
		["infinity-coil-block"]  = "spacetime-coil-block",
		["spacetime-coil-block"] = "eternal-coil-block",
	},
	--- MAX machines (141-fork-max.lua): magmatter cable; the eternal coil stays (GT has no coil above it)
	max = {
		["universium-cable"]     = "magmatter-cable",
		["spacetime-coil-block"] = "eternal-coil-block",
	},
}
local function item_exists(n)
	for t, _ in pairs(defines.prototypes.item) do
		if data.raw[t] and data.raw[t][n] then return true end
	end
	return false
end
local function shift_name(n, to_tier)
	local special = SPECIAL_SHIFT[to_tier] or {}
	if special[n] and item_exists(special[n]) then return special[n] end
	local t, rest = n:match("^(%a+)%-(.+)$")
	if t and TIER_INDEX[t] and TIERS[TIER_INDEX[t] + 1] then
		local shifted = TIERS[TIER_INDEX[t] + 1] .. "-" .. rest
		if item_exists(shifted) then return shifted end
	end
	return n
end
local function shift_list(list, to_tier)
	local out = {}
	for _, i in pairs(list or {}) do
		local c = table.deepcopy(i)
		if c.type ~= "fluid" then c.name = shift_name(c.name, to_tier) end
		table.insert(out, c)
	end
	return out
end

--- Machines that get generated sprites (from GT textures)
IV_BASIC_MACHINES = {
	"wiremill", "bending-machine", "extruder", "rock-crusher", "lathe", "macerator", "centrifuge",
	"extractor", "electrolyzer", "assembling-machine", "cutting-machine",
	"canning-machine", "mixer", "ore-washer", "laser-engraver", "fluid-solidifier", "chemical-bath",
	"polarizer", "circuit-assembler", "autoclave", "alloy-smelter", "compressor", "forge-hammer", "arc-furnace", "forming-press", "electric-furnace",
}
--- Multiblocks that come as an upgrade of the EV version (graphics of the EV version with energy hatches of the tier)
IV_UPGRADE_MACHINES = {
	"electric-blast-furnace", "vacuum-freezer", "large-chemical-reactor", "microverse-projector",
	"tall-distillation-tower", "short-distillation-tower", "implosion-compressor", "cracker",
	"multismelter", "pyrolyse-oven", "drilling-rig", "alloy-blast-smelter",
}

local UPGRADE_HATCHES = {}
for _, base in pairs(IV_UPGRADE_MACHINES) do UPGRADE_HATCHES[base] = true end

--- Upgrade multiblocks keep the EV sprite of their source; the GT energy hatches of their tier are an extra
--- layer of the same size on it (<tier>-<base>-hatches.png from tools/gen_sprites.py, UPGRADE_MULTIBLOCKS).
--- The copy of the previous tier brings that tier's layer along, it is replaced.
local function set_tier_hatches(m, name)
	for _, key in pairs({ "idle_animation", "animation" }) do
		local anim = m.graphics_set and m.graphics_set[key]
		if anim then
			if not anim.layers then
				anim = { layers = { anim } }
				m.graphics_set[key] = anim
			end
			local layers = {}
			for _, l in pairs(anim.layers) do
				if not (l.filename or ""):match("%-hatches%.png$") then layers[#layers + 1] = l end
			end
			local b = layers[1]
			layers[#layers + 1] = {
				filename = SPRITE_PATH .. name .. "-hatches.png",
				width = b.width, height = b.height, scale = b.scale, shift = b.shift,
				frame_count = 1, repeat_count = (b.frame_count or 1) * (b.repeat_count or 1),
				animation_speed = b.animation_speed,
			}
			anim.layers = layers
		end
	end
end

--- Issue #148: a basic machine one tier up keeps the graphics set of its source (size, frame count, animation speed: in
--- the end the EV machine's, made by make_electric_machine from upstream's asset) with its own files, upstream's asset with
--- the casing in the tier's colour (tools/gen_sprites.py, basic_machine).
local function tier_graphics(src, name)
	local g = src.graphics_set and table.deepcopy(src.graphics_set)
	if not (g and g.idle_animation and g.animation) then return nil end
	for key, suffix in pairs({ idle_animation = "-idle.png", animation = "-working.png" }) do
		for _, layer in pairs(g[key].layers or { g[key] }) do layer.filename = SPRITE_PATH .. name .. suffix end
	end
	return g
end

--- Create a machine one tier up (entity, item, recipe). Global so 110-fork-luv.lua can use it.
--- sprite_frames: the machine gets the sprites of tools/gen_sprites.py; a basic machine (a graphics set with an idle and
--- a working animation) keeps its source's frame count, other machines get sprite_frames frames.
function fork_make_tier_machine(base, from_tier, to_tier, sprite_frames, unlock_tech)
	local src_name, new_name = from_tier .. "-" .. base, to_tier .. "-" .. base
	local hatches = not sprite_frames and UPGRADE_HATCHES[base]
	local src = data.raw["assembling-machine"][src_name]
	if not src then log("FORK-MACHINE: no source machine " .. src_name) return end
	local categories = table.deepcopy(src.crafting_categories)
	local extra = {}
	for _, c in pairs(categories) do
		local ct, rest = c:match("^(%a+)%-(.+)$")
		if ct and TIER_INDEX[ct] then add_unique(extra, tier_categories(rest, to_tier)) end
	end
	categories = add_unique(categories, extra)

	local icon = (sprite_frames or hatches) and ("__gregtorio-continued__/graphics/icons/fork/" .. new_name .. ".png") or nil
	local m = clone_machine{
		name = new_name, source = src_name, categories = categories,
		crafting_speed = src.crafting_speed * 2,
		energy_usage = scale_energy(src.energy_usage, 2),
		sprite = sprite_frames and { new_name, sprite_frames } or nil,
		icon = icon,
	}
	if m and hatches then set_tier_hatches(m, new_name) end
	if m and sprite_frames then m.graphics_set = tier_graphics(src, new_name) or m.graphics_set end

	--- Item
	local src_item = data.raw.item[src_name]
	local item = table.deepcopy(src_item)
	item.name = new_name
	item.place_result = new_name
	item.order = (src_item.order or "") .. "-" .. to_tier
	local sg = item.subgroup or ""
	if sg:match("age%-production%-machine$") then item.subgroup = to_tier .. "-age-production-machine" end
	if sg:match("age%-multiblocks$") then item.subgroup = "subgroup-" .. to_tier .. "-age-multiblocks" end
	if icon then item.icon = icon; item.icon_size = 32 end
	data:extend({ item })

	--- Recipe
	local src_recipe = data.raw.recipe[src_name]
	local r = table.deepcopy(src_recipe)
	r.name = new_name
	r.enabled = false
	r.ingredients = shift_list(src_recipe.ingredients, to_tier)
	r.results = shift_list(src_recipe.results, to_tier)
	for _, res in pairs(r.results) do if res.name == src_name then res.name = new_name end end
	if r.main_product then r.main_product = new_name end
	--- Upgrade multiblocks: the previous version goes in, not the new version itself
	for _, ing in pairs(r.ingredients) do if ing.name == new_name then ing.name = src_name end end
	data:extend({ r })
	if unlock_tech then fork_add_unlock(unlock_tech, new_name) end
end

for _, t in pairs({ "iv", "luv", "zpm" }) do
	if not data.raw["item-subgroup"][t .. "-age-production-machine"] then
		data:extend({ { type = "item-subgroup", name = t .. "-age-production-machine", group = "production", order = "i-z-" .. t } })
	end
end

for _, base in pairs(IV_BASIC_MACHINES) do fork_make_tier_machine(base, "ev", "iv", 6, "iv-machines") end
for _, base in pairs(IV_UPGRADE_MACHINES) do fork_make_tier_machine(base, "ev", "iv", nil, "iv-machines") end



--------------------------------------------------------------------------------
--- 4) IV MULTIBLOCKS (GT++ industrial machines), items from 20-iv-age-entity.lua
---    Process all recipes of their machine family up to IV, twice as fast as IV.
--------------------------------------------------------------------------------

local IV_MULTIBLOCKS = {
	-- item/entity                          source (fluid ports)   category family
	{ "iv-industrial-maceration-stack",     "ev-macerator",        { "macerator-recipes" } },
	{ "iv-industrial-wire-factory",         "ev-wiremill",         { "wiremill-recipes" } },
	{ "iv-industrial-material-press",       "ev-bending-machine",  { "bending-machine-recipes" } },
	{ "iv-large-electric-compressor",       "ev-compressor",       { "compressor-recipes" } },
	{ "iv-magnetic-flux-exhibiter",         "ev-polarizer",        { "polarizer-recipes" } },
	{ "iv-fluid-shaper",                    "ev-fluid-solidifier", { "fluid-solidifier-recipes" } },
	{ "iv-industrial-cutting-factory",      "ev-cutting-machine",  { "cutting-machine-recipes" } },
	{ "iv-chemical-bath-plant",             "ev-chemical-bath",    { "chemical-bath-recipes" } },
	{ "iv-industrial-electrolyzer",         "ev-electrolyzer",     { "electrolyzer-recipes" } },
	{ "iv-industrial-precision-lathe",      "ev-lathe",            { "lathe-recipes" } },
	{ "iv-large-extractor",                 "ev-extractor",        { "extractor-recipes" } },
	{ "iv-hyper-intensity-laser-engraver",  "ev-laser-engraver",   { "laser-engraver-recipes" } },
	{ "iv-industrial-extrusion-machine",    "ev-extruder",         { "extruder-recipes" } },
	{ "iv-industrial-centrifuge",           "ev-centrifuge",       { "centrifuge-recipes" } },
	{ "iv-industrial-mixer",                "ev-mixer",            { "mixer-recipes" } },
	{ "iv-turbocan-pro",                    "ev-canning-machine",  { "canning-machine-recipes" } },
	{ "iv-zyngen",                          "ev-alloy-smelter",    { "alloy-smelter-recipes" } },
}

for _, mb in pairs(IV_MULTIBLOCKS) do
	local name, source, families = mb[1], mb[2], mb[3]
	if data.raw.item[name] then
		local categories = {}
		for _, fam in pairs(families) do add_unique(categories, tier_categories(fam, "iv")) end
		local src = data.raw["assembling-machine"][source]
		clone_machine{
			name = name, source = source, categories = categories,
			crafting_speed = 32,
			energy_usage = src and scale_energy(src.energy_usage, 4) or EU16_IV,
			fast_replaceable_group = "fr-" .. name,
			icon = data.raw.item[name].icon,
			sprite = { name, 1 },
		}
		set_place_result(name, name)
	else
		log("FORK-MACHINE: missing IV multiblock item: " .. name)
	end
end

--- Upstream bugs in the IV multiblock recipes
do
	--- The wire factory needed itself instead of its controller
	local r = data.raw.recipe["iv-industrial-wire-factory"]
	if r then
		for _, ing in pairs(r.ingredients) do
			if ing.name == "iv-industrial-wire-factory" then ing.name = "industrial-wire-factory-controller" end
		end
	end
	--- The precision lathe had the electrolyzer's icon
	local it = data.raw.item["iv-industrial-precision-lathe"]
	if it then it.icon = ICON_PATH .. "industrial-precision-lathe.png" end
	--- Zyngen had the industrial mixer's icon
	local zy = data.raw.item["iv-zyngen"]
	if zy then zy.icon = ICON_PATH .. "zyngen.png" end
end
