#!/usr/bin/env python3
"""Replaces the "NYI" (not yet implemented) placeholder technology icons.

Input: a TSV with one technology per line, "<tech-name>\\t<__Gregtorio__/... icon path>",
naming the item or fluid whose icon should represent the technology (usually the main
product it unlocks: the material, machine or component).

Output:
  graphics/technology/fork/<tech-name>.png   256x256, the item icon scaled up pixel-exact
  prototypes/fork-tech-icons.lua             list of techs that have such an icon; only
                                             those are switched over in 199-fork-finalize.lua,
                                             so a missing file can never crash the game

    python tools/gen_tech_icons.py tech-icons.tsv
"""
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "graphics/technology/fork"
LUA = ROOT / "prototypes/fork-tech-icons.lua"
SIZE = 256


def render(src):
    img = Image.open(src).convert("RGBA")
    w, h = img.size
    img = img.crop((0, 0, min(w, h), min(w, h)))      # first frame / mipmap level
    bbox = img.getbbox() or (0, 0, img.width, img.height)
    img = img.crop(bbox)
    scale = max(1, (SIZE - 32) // max(img.size))        # integer factor keeps pixels crisp
    img = img.resize((img.width * scale, img.height * scale), Image.NEAREST)
    out = Image.new("RGBA", (SIZE, SIZE))
    out.paste(img, ((SIZE - img.width) // 2, (SIZE - img.height) // 2), img)
    return out


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    done = []
    for line in Path(sys.argv[1]).read_text().splitlines():
        if "\t" not in line:
            continue
        tech, icon = line.split("\t", 1)
        src = ROOT / icon.replace("__Gregtorio__/", "", 1)
        if not src.exists():
            print(f"skip {tech}: {icon} not found")
            continue
        render(src).save(OUT / f"{tech}.png")
        done.append(tech)
    body = "\n".join(f'\t["{t}"] = true,' for t in sorted(done))
    LUA.write_text("--- Generated by tools/gen_tech_icons.py: technologies with an icon in\n"
                   "--- graphics/technology/fork/ (replaces the NYI placeholder).\n"
                   f"FORK_TECH_ICONS = {{\n{body}\n}}\n", encoding="utf-8")
    print(f"{len(done)} technology icons written")


if __name__ == "__main__":
    main()
