#!/usr/bin/env python3
"""Replaces the "NYI" (not yet implemented) placeholder technology icons.

Input: a TSV with one technology per line, "<tech-name>\\t<__gregtorio-continued__/... icon path>",
naming the item or fluid whose icon should represent the technology (usually the main
product it unlocks: the material, machine or component). tools/tech-icons.tsv lists every
technology with such an icon; new technologies go there too, so a changed item icon (for example
from tools/gen_gt_icons.py) is carried over to its technology by running this again.

Items are scaled up pixel-exact. Fluids are drawn the way GregTech shows fluids as items:
a GT fluid cell filled with the fluid's color (taken from its Gregtorio fluid icon), which
needs the GT5-Unofficial textures (--gt).

Output:
  graphics/technology/fork/<tech-name>.png   256x256
  prototypes/fork-tech-icons.lua             list of techs that have such an icon (merged with the
                                             earlier list, as long as their icon exists); only
                                             those are switched over in 199-fork-finalize.lua,
                                             so a missing file can never crash the game

    python tools/gen_tech_icons.py --gt C:/00_Repositories/GT5-Unofficial      (tools/tech-icons.tsv)
    python tools/gen_tech_icons.py other.tsv --gt C:/00_Repositories/GT5-Unofficial

An icon whose pixels did not change is not rewritten.
"""
import argparse, re, warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "graphics/technology/fork"
LUA = ROOT / "prototypes/fork-tech-icons.lua"
SIZE = 256


def first_frame(img):
    w, h = img.size
    return img.crop((0, 0, min(w, h), min(w, h)))       # first animation frame / mipmap level


def upscale(img):
    img = first_frame(img)
    bbox = img.getbbox() or (0, 0, img.width, img.height)
    img = img.crop(bbox)
    scale = max(1, (SIZE - 32) // max(img.size))         # integer factor keeps pixels crisp
    img = img.resize((img.width * scale, img.height * scale), Image.NEAREST)
    out = Image.new("RGBA", (SIZE, SIZE))
    out.paste(img, ((SIZE - img.width) // 2, (SIZE - img.height) // 2), img)
    return out


def average_color(img):
    px = [p for p in first_frame(img).convert("RGBA").getdata() if p[3] > 128]
    if not px:
        return (128, 128, 128)
    return tuple(sum(p[i] for p in px) // len(px) for i in range(3))


def fluid_cell(fluid_icon, gt):
    """GT fluid cell: grayscale fluid part tinted with the fluid color, glass/metal overlay on top."""
    base = gt / "src/main/resources/assets/gregtech/textures/items/materialicons/FLUID"
    cell = first_frame(Image.open(base / "cell.png").convert("RGBA"))
    overlay = first_frame(Image.open(base / "cell_OVERLAY.png").convert("RGBA"))
    r, g, b = average_color(Image.open(fluid_icon))
    px = cell.load()
    for y in range(cell.height):
        for x in range(cell.width):
            cr, cg, cb, ca = px[x, y]
            if ca:
                px[x, y] = (cr * r // 255, cg * g // 255, cb * b // 255, ca)
    cell.alpha_composite(overlay)
    return upscale(cell)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=Path, nargs="?", default=ROOT / "tools/tech-icons.tsv")
    ap.add_argument("--gt", type=Path, help="GT5-Unofficial checkout (needed for fluid techs)")
    a = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    done, written = [], 0
    for line in a.tsv.read_text().splitlines():
        if "\t" not in line:
            continue
        tech, icon = line.split("\t", 1)
        src = ROOT / icon.replace("__gregtorio-continued__/", "", 1)
        if not src.exists():
            print(f"skip {tech}: {icon} not found")
            continue
        if "/graphics/fluids/" in icon:
            if not a.gt:
                print(f"skip {tech}: fluid icon needs --gt")
                continue
            img = fluid_cell(src, a.gt)
        else:
            img = upscale(Image.open(src).convert("RGBA"))
        target = OUT / f"{tech}.png"
        if not (target.exists() and Image.open(target).convert("RGBA").tobytes() == img.tobytes()):
            img.save(target, optimize=True)
            written += 1
        done.append(tech)
    # keep the techs of earlier runs whose icon is still there
    if LUA.exists():
        for t in re.findall(r'\["([^"]+)"\] = true', LUA.read_text(encoding="utf-8")):
            if (OUT / f"{t}.png").exists() and t not in done:
                done.append(t)
    body = "\n".join(f'\t["{t}"] = true,' for t in sorted(done))
    LUA.write_text("--- Generated by tools/gen_tech_icons.py: technologies with an icon in\n"
                   "--- graphics/technology/fork/ (replaces the NYI placeholder).\n"
                   f"FORK_TECH_ICONS = {{\n{body}\n}}\n", encoding="utf-8")
    print(f"{written} technology icons written ({len(done) - written} unchanged), {len(done)} listed in {LUA.name}")


if __name__ == "__main__":
    main()
